site_name: Pillar Youtube Uploader

theme:
  name: "material"
  palette:
    scheme: slate
    primary: indigo
    accent: blue
  logo: pillargg.png
  favicon: pillargg.png

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering: 
          show_sources: false
      watch:
        - youtube_upload